workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    clerk-backend-php:
        inputs:
            - location: ./openapi.json
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    clerk-php:
        target: php
        source: clerk-backend-php
        publish:
            packagist:
                username: clerkinc
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi-code-samples
            blocking: false
