workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    clerk-backend-php:
        inputs:
            - location: ./openapi.json
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    my-first-target:
        target: php
        source: clerk-backend-php
